**Summary:**
Far too often students are tormented by Word or other word processors that
cannot handle equations, figures or tables in a reliable and satisfying way.
This template shows how Quarto and Jupyter Notebooks can produce good-looking
PDF reports through LaTeX. The content ends up in focus, not the formatting.
Study this document and its cells to learn how it is put together. Keep the
report tidy, short and to the point!

## Introduction: how to write modern reports

This template uses [Quarto](https://quarto.org/) together with Jupyter Notebooks to produce PDF reports through LaTeX. Unlike Overleaf, we write in ordinary Jupyter Notebooks and use LaTeX *only* for mathematical equations. Quarto takes care of all the formatting, the numbering of sections, equations and figures, and the references, automatically.

### Installation

To render this template you need:

1. **Python and Jupyter**, see the [installation guide](https://python.ju.se/python_installation.html)
2. **Quarto** from [quarto.org](https://quarto.org/docs/get-started/). Choose "Install for me only" if you do not have administrator rights.
3. **A LaTeX distribution** for PDF rendering. Check whether you already have one with `pdflatex --version`. If not:
    - Linux: `sudo apt install texlive-full`
    - macOS: [MacTeX](https://tug.org/mactex/)
    - Windows: [MiKTeX](https://miktex.org/)
    - Or TinyTeX (small, about 250 MB): `quarto install tinytex`
4. **VS Code** with the [Quarto](https://marketplace.visualstudio.com/items?itemName=quarto.quarto) and [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) extensions

See [PDF Reports with LaTeX](https://python.ju.se/ProgrammingFundamentals/writing_documentation.html) for a full walkthrough of Quarto, LaTeX maths and troubleshooting.

### Workflow

1. Open this notebook in VS Code
2. Edit the text in markdown cells, add equations with LaTeX syntax
3. Add Python code cells for figures and calculations
4. Render to PDF with one of the following commands:

```bash
quarto preview report.ipynb --to pdf
```

`quarto preview` renders the PDF and opens it automatically. It also watches the file, so every time you save the notebook the PDF is re-rendered and updated. Perfect while writing, just like Overleaf's live preview. Stop it with `Ctrl+C` in the terminal.

```bash
quarto render report.ipynb --to pdf --execute
```

`quarto render` renders the PDF once, without watching. The `--execute` flag runs every code cell during rendering, which makes the results reproducible. Use this for the final version.

### Document structure

The whole report lives in a single notebook file. The metadata (title, authors, format) is defined in the YAML block in the first cell (a *raw* cell). Markdown cells hold text and equations, and code cells generate figures and tables automatically.

## Figures

See @fig-chad, a graph of the very highest quality.

![Look at this graph](graphics/chad.jpg){#fig-chad width=60%}

### How do we handle figures?

Look at the source of the notebook cells to see how a figure is included with a caption and a reference. The syntax is:

```markdown
![Caption](path/to/image.jpg){#fig-label width=60%}
```

Then refer to it in the text with `@fig-label`. Quarto numbers the figures for you.

We always include a caption and describe the figure properly. If the figure is not our own, we cite the source.

### Vector graphics

Always aim for vector images (SVG, PDF), which can be scaled freely without losing quality. You can use PowerPoint or [Inkscape](https://inkscape.org/) to draw graphics and export them as SVG.

### Figures from Python code

One of Quarto's great strengths is that Python code can generate figures directly in the report. The code cell below generates @fig-sinewave using these Quarto comments:

```python
#| label: fig-sinewave
#| fig-cap: "A sine wave generated with Python"
#| echo: true
```

- `label: fig-sinewave` makes the figure referable with `@fig-sinewave`
- `fig-cap` sets the caption
- `echo: true` shows the code in the PDF (set it to `false` to hide it)

In [1]:
#| label: fig-sinewave
#| fig-cap: "A sine wave generated with Python"
#| echo: true

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 100)
plt.plot(x, np.sin(x))
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.grid(True, alpha=0.3)
plt.show()

<Figure size 1650x1050 with 1 Axes>

The code cell above uses Quarto comments (`#|`) to control how it appears, see @tbl-codecell.

| Option | Effect |
|-----------|--------|
| `#\| echo: true` | Show the code (default) |
| `#\| echo: false` | Hide the code, show only the figure |
| `#\| output: false` | Hide the output |
| `#\| warning: false` | Suppress warnings |
| `#\| label: fig-name` | Make the figure referable |
| `#\| fig-cap: "..."` | Caption |

: Quarto comments for code cells {#tbl-codecell}

## Mathematical notation

```{=latex}
\vspace{0.05\paperheight}
\epigraph{``An equation says more than a thousand figures''}{--- \textup{Fredrik Larsson}}
\vspace{0.05\paperheight}
```

An engineer has to be precise in their language to communicate efficiently and avoid misunderstandings. The point of being precise is to let the reader follow the reasoning and reproduce the work. Below is the kind of mathematical notation a mechanical engineer inflicts on their surroundings.

### Equations in text and on their own line

Use single dollar signs `$...$` for maths in running text and double ones `$$...$$` for centred equations.

The model rests on kinetic energy being converted into potential energy plus some kinetic energy: the train has an initial velocity $v_{0}$ that takes it up to the height $h$, where it has the velocity $v$.

$$
\frac{1}{2}mv_{0}^{2}=mgh+\frac{1}{2}mv^{2}
$$

Solving for $v$

$$
v=\sqrt{v_{0}^{2}-2gh}
$$ {#eq-velocity}

In the positive normal direction we get

$$
N-mg\cos\theta=ma_{c}
$$

The normal acceleration along a curved path is given by

$$
a_{c}=\frac{v^{2}}{r}
$$

Substitution gives

$$
N=\frac{mv^{2}}{r}+mg\cos\theta
$$

and we divide out the mass and $g$ to express it as a number of $g$ "forces"

$$
\frac{N}{mg}=\frac{v^{2}}{rg}+\cos\theta=:G
$$

A constant normal acceleration implies

$$
a_{c}=Cg=\frac{v^{2}}{r}
$$ {#eq-constnormacc}

Putting @eq-velocity into @eq-constnormacc

$$
a_{c}=Cg=\frac{v_{0}^{2}-2gy}{Cg}
$$

$$
\overset{\text{let }h=y}{\Rightarrow}\boxed{r=\frac{v_{0}^{2}-2gh}{Cg}}
$$

The relation between arc length, radius and angle is

$$
ds=rd\theta\Rightarrow\frac{d\theta}{ds}=\frac{1}{r}
$$

which leads to a final, rather pleasant ordinary differential equation, solved numerically with Python.

$$
\text{ODE}\begin{cases}
\frac{d\theta}{ds}=\frac{1}{r}\\[6pt]
\frac{dx}{ds}=\cos\theta\\[6pt]
\frac{dy}{ds}=\sin\theta
\end{cases}
$$

### Vectors and matrices

- Vectors are normally set in bold: $\bm{a}$ and $\bm{\varphi}$, or with `\bm`: $\bm{\sigma}$.
- Italics for tensors: $\mathcal{T},\mathcal{C}_{ijkl}$. A matrix can be written $\bm{A}$ and its numerical version $\mathbf{A}$.
- There are plenty of ways to write a transpose. The lazy one: $\bm{a}^{T}$, the less lazy $\bm{a}^{\mathrm{T}}$, and the arguably prettier $\bm{a}^{\mathsf{T}}$.
- Force vectors are written $\bm F$ or $\mathbf F$

The basis function matrix is defined as

$$
\bm{\Phi}:=\begin{bmatrix}\varphi_{1} & 0 & 0 & \varphi_{2} & 0 & 0 & \cdots\\
0 & \varphi_{1} & 0 & 0 & \varphi_{2} & 0 & \cdots\\
0 & 0 & \varphi_{1} & 0 & 0 & \varphi_{2} & \cdots
\end{bmatrix}
$$ {#eq-fidiscrete}

### Large matrices

Matrices containing fractions sometimes need more room between the rows. Here we use raw LaTeX:

```{=latex}
\renewcommand*{\arraystretch}{2.5}
$$\bm{J}(\xi,\eta,\zeta)=\begin{bmatrix}\dfrac{\partial x_{h}}{\partial\xi} & \dfrac{\partial y_{h}}{\partial\xi} & \dfrac{\partial z_{h}}{\partial\xi}\\
\dfrac{\partial x_{h}}{\partial\eta} & \dfrac{\partial y_{h}}{\partial\eta} & \dfrac{\partial z_{h}}{\partial\eta}\\
\dfrac{\partial x_{h}}{\partial\zeta} & \dfrac{\partial y_{h}}{\partial\zeta} & \dfrac{\partial z_{h}}{\partial\zeta}
\end{bmatrix}$$
\renewcommand*{\arraystretch}{1}
```

### Numerical evaluation

Sometimes a calculation or the evaluation of a function has to be written out:

$$
\frac{dy}{dt}=\dot{y}=\frac{125\pi}{200}\sin\left(\frac{50\pi}{200}\right)\cdot150=\frac{375\pi\sqrt{2}}{8}\approx208\text{ m/s}
$$

Every time the symbol $*$ is misused as a multiplication sign, a mathematician or an engineer weeps a little on the inside.

$$f*g$$

means the convolution^[https://en.wikipedia.org/wiki/Convolution] of $f$ with $g$.

### Gaussian integration

$$
\int_{0}^{1}f(x)\ dx\approx\sum_{i=1}^{n}f(x_{i})w_{i}
$$

An $n$-point Gaussian quadrature is exact for polynomials of degree $2n-1$ or lower. See @tbl-gauss.

| Gauss order $n$ | Polynomial degree | Weights $w_{i}$ | Points $x_{i}$ |
|:--:|:--:|:--:|:--:|
| 1 | 1 | $1$ | $\frac{1}{2}$ |
| 2 | 3 | $\frac{1}{2},\ \frac{1}{2}$ | $\frac{1}{2}\pm\frac{\sqrt{3}}{6}$ |
| 3 | 5 | $\frac{5}{18},\ \frac{4}{9},\ \frac{5}{18}$ | See below |

: Gaussian quadrature for $\xi\in[0,1]$ {#tbl-gauss}

Gauss points for $n=3$: $\frac{1}{2}-\frac{\sqrt{15}}{10}$, $\frac{1}{2}$, $\frac{1}{2}+\frac{\sqrt{15}}{10}$.

For arbitrary Gauss orders and intervals you can use the Golub-Welsch algorithm.

## Tables

### Simple tables in markdown

| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Data     | Data     | Data     |
| Data     | Data     | Data     |

### Complex tables with LaTeX

For tables containing equations or special formatting you can use raw LaTeX. With `\resizebox{\textwidth}{!}{...}` the table is scaled to the width of the text:

```{=latex}
\begin{center}
\resizebox{\textwidth}{!}{%
\begin{tabular}{c|c|c}
State of stress & Boundary Conditions & von Mises Equations\\
\hline
 &  & \\
General 3D & No restrictions & $\sigma_{v}=\sqrt{\frac{1}{2}\left[\left(\sigma_{x}-\sigma_{y}\right)^{2}+\left(\sigma_{y}-\sigma_{z}\right)^{2}+\left(\sigma_{z}-\sigma_{x}\right)^{2}+6\left(\sigma_{xy}^{2}+\sigma_{yz}^{2}+\sigma_{zx}^{2}\right)\right]}$\\
General plane stress (2D) & $\sigma_{z}=\sigma_{yz}=\sigma_{zx}=0$ & $\sigma_{v}=\sqrt{\sigma_{x}^{2}-\sigma_{x}\sigma_{y}+\sigma_{y}^{2}+3\sigma_{xy}^{2}}$\\
\end{tabular}}
\end{center}
```

## Including code in reports

In Quarto, Python code is shown straight from the code cells. Control what is displayed with `#|` comments at the top of the cell:

- `#| echo: true` shows the code (default)
- `#| echo: false` hides the code and shows only the result
- `#| output: false` hides the result

Below is a code example with `#| echo: true`:

In [2]:
#| echo: true

import numpy as np

# Element loop example
n_elements = 4
n_nodes = n_elements + 1
S = np.zeros((n_nodes, n_nodes))
F = np.zeros(n_nodes)

for iel in range(n_elements):
    inod = [iel, iel + 1]       # Element nodes
    Sk = np.array([[1, -1],
                   [-1, 1]])    # Element stiffness
    fk = np.array([0.5, 0.5])   # Element force

    # Assembly
    ix = np.ix_(inod, inod)
    S[ix] += Sk
    F[inod] += fk

print("Stiffness matrix:")
print(S)
print("Force vector:", F)

Stiffness matrix:
[[ 1. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  1.]]
Force vector: [0.5 1.  1.  1.  0.5]


## References

Quarto handles references through `.bib` files. In the YAML block we write:

```yaml
bibliography: library.bib
```

Then cite with `@key` or `[@key]`:

- `@Stromberg2012` gives: @Stromberg2012
- `[@Johannesson2013; @Logan2012]` gives: [@Johannesson2013; @Logan2012]

Sometimes you need to refer to the same clever people who did good things, see [@Johannesson2013; @Logan2012; @Lundkvist1997; @Stromberg2012].

### Reference style

The reference style is changed with a CSL file in the YAML. For IEEE style, for example:

```yaml
csl: ieee.csl
```

Download `ieee.csl` from the [Zotero Style Repository](https://www.zotero.org/styles/ieee) and put the file in the same folder as the notebook. Common styles:

| Style | File name | Format |
|------|---------|--------|
| IEEE | `ieee.csl` | [1], [2], [3] |
| APA | `apa.csl` | (Strömberg, 2012) |
| Vancouver | `vancouver.csl` | (1), (2), (3) |

### BibTeX format

The reference data is stored in `library.bib` in BibTeX format:

```bibtex
@Book{Callister2011,
  author  = {{W. D Callister and D. G Rethwisch}},
  title   = {Materials Science and Engineering},
  year    = {2011},
  volume  = {SI version},
  edition = {8},
}
```

You can search for "title + author bibtex" or use the cite button in Google Scholar and pick the BibTeX link.

Every cited reference is added automatically at the end of the document.